config/routes.rb
Rails.application.routes.draw do
  get 'players/new' => 'players#new'

  post 'players' => 'players#create'

  delete 'players/logout' => 'players#destroy'

  devise_for :users
  resources :users, only: [:index, :show]
  
  resources :games, only: [:index, :show]
  
  post 'results' => 'results#create'

  root 'games#index'

  get 'matches/:id' => 'matches#show'
end

app/views/partials/_bar_line_chart.erb
<div class="LineBarChart">

<script>
<%dataset = []%>
<% SubSkill.where(skill_name: "addition").each do |skill| %>
  <%p "$"*50 %>
  <%p skill %>
  <% dataset << User.find(1).percent('correct', skill.skill_name, skill.name, 1)*10 %>
<% end %>
//Width and height
var w = 500;
var h = 300;
//Create SVG element
var svg = d3.select("body")
            .append("svg")
            .attr("width", w)
            .attr("height", h);

var bars = svg.selectAll("rect")
   .data(<%=dataset%>)
   .enter()
   .append("rect")
   .attr("fill", "teal")
   .attr("x", function(d, i) {
    return i * (w /<%=dataset.length%>);
})
   .attr("y", h - 1)
   .attr("width", 25)
   .attr("height", 1);

bars.transition()
  .duration(1000)
  .delay(100)
  .attr("y", function(d) {
    return h - (d * 4);  //Height minus data value
})
   .attr("height", function(d) {
    return d * 4;
})
</script>
</div>

app/views/partials/_flash.erb
<% if flash[:errors] %>
	
	<% flash.each do |name, msg| %>
		<% if msg.class == Array %>
			<% msg.each do |message| %>
				<%= content_tag :div, message, :id => "flash_#{name}" %>
			<% end %>
		<% else %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
	<% end %>
<% end %>

app/views/partials/_navBar.html.erb
<div class="navBar">
  <h1 class="title"><a href="/">Mathio Party</a></h1>
  <div class="games-links">

    <% if current_user  %>
      <%= link_to 'Frogger', game_path(1) %>
      <%= link_to 'Flappy Math', game_path(2) %>
      <%= link_to 'Invasion', game_path(3) %>
      <%= link_to 'Duck Hunt', game_path(4) %>
    <% end %>
  </div>

  <div class="navbar-left">
    <% if current_user  %>
      <%= link_to 'Leaderboards', users_path %>
      <%= link_to 'Profile Page', user_path(current_user.id) %>
    <% end %>
  </div>

  <div class="login">
    <% if current_user %>
    	<%= link_to "Logout, #{current_user.username}", destroy_user_session_path, method: :delete %>

      <% if !player2_logged_in? %>
        <%= link_to 'Player 2 Login', players_new_path %>
      <% else %>
        <%= link_to "Logout, #{current_player2.username}", players_logout_path, method: :delete %>
      <% end %>

    <% else %>
    	<%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Sign Up', new_user_registration_path  %>
    <% end %>
  </div>
</div>

app/views/partials/_radarChart.html.erb
<div class="radarChart">
  <div class="radarChartDescription">
    <p>This chart shows the percent of correctly answered multiplication questions with the given number </p>
  </div>
</div>

<script>
  // Set-Up
  var margin = {top: 100, right: 100, bottom: 100, left: 100},
    width = Math.min(700, window.innerWidth - 10) - margin.left - margin.right,
    height = Math.min(width, window.innerHeight - margin.top - margin.bottom - 20);

  // Data
  var data = [
        [//match 1
        <% 8.times do |num| %>
        <% p "$" * 500 %>
        <% p user %>
          <% val = User.find(1).percent('correct', skill, "#{num} times table", 1)%>
          {axis:<%= num %>,value:<%= val %>},
        <% end %>
        {axis:"9",value:<%= User.find(1).percent('correct', skill, "9 times table", 1)%>}
        ],
        [//match 2
        <% 8.times do |num| %>
          <% val = User.find(2).percent('correct', skill, "#{num} times table", 2)%>
          {axis:<%= num %>,value:<%= val %>},
        <% end %>
        {axis:"9",value:<%= User.find(2).percent('correct', skill, "9 times table", 2)%>}
        ]
      ];

  // Draw the Chart
  var color = d3.scaleOrdinal()
    .range(["#EDC951","#CC333F","#00A0B0"]);

  var radarChartOptions = {
    w: width,
    h: height,
    margin: margin,
    maxValue: 0.5,
    levels: 5,
    roundStrokes: true,
    color: color
  };
  //Call function to draw the Radar chart
  RadarChart(".radarChart", data, radarChartOptions);
</script>