config/routes.rb
Rails.application.routes.draw do
  get 'players/new' => 'players#new'

  post 'players' => 'players#create'

  delete 'players/logout' => 'players#destroy'

  devise_for :users
  resources :users, only: [:index, :show]
  
  resources :games, only: [:index, :show]
  
  post 'results' => 'results#create'

  root 'games#index'

  get 'matches/:id' => 'matches#show'
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
  end

  def create
  	@current_player2 = User.find_by(email: player_params[:email])
    if @current_player2 == current_user
      flash[:errors] = ['You are already signed in!']
      return render 'new'
    end

  	if @current_player2 && @current_player2.valid_password?(player_params[:password])
  		session[:player2] = @current_player2.id
  		redirect_to root_path
  	else
  		flash[:errors] = ['Invalid login']
  		render 'new'
  	end
  end

  def destroy
  	session[:player2] = nil
  	redirect_to root_path
  end

  private
  def player_params
  	params.require(:player).permit(:email, :password)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/new.html.erb
<div class="playerTwoLogin">
	<h2>Welcome Player 2! Login here...</h2>

	<div class="new_user">
		<%= form_for :player, url: players_path do |f| %>

			<div class="flash-errors">
				<%= render "partials/flash" %>
			</div>

			<p>
				<%= f.label :Email %><br>
				<%= f.text_field :email %>
			</p>

			<p>
				<%= f.label :Password %><br>
				<%= f.password_field :password %>
			</p>

			<div class="playerTwoLoginButton">
				<%= f.submit 'Login' %>
			</div>
		<% end %>
	</div>
</div>